[package]
name = "account-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
account-libs = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }